#!/bin/bash

#This demonstrates two ways to display multi-line stings or strings that contain multiple lines

#here are two methods of inputting the string value

####------------
text1="This is multiple lines
	in a string
        using double quotes
	and tabs
  here is a line with spaces
note both are displayed"

text2=$(cat <<-END
This is an alternative way to 
	enter text, note
	tabs are ignored
  and spaces are not ignored
  they are displayed
END
)
#####------------------

#this will run the lines together
echo $text1

echo $text2


#this will retain formatting
echo "$text1"
echo "$text2"

